### ISSUE TITLE
use map for parameter names -> types in GeneralSensorConfig

### ISSUE THREAD

**Issue by a-enz** [nervousnet/nervousnet-HUB-iOS#12]
makes it much more convenient to look up types

**Comment by lewinernst** [comment]
I think i agree with both emails, but i'll have to check properly tomorrow. I think it might introduce more complicated handling of false configurations, since we can't force types for incoming jasons.

**Comment by lewinernst** [comment]
*json

**Comment by a-enz** [comment]
This issue is getting more and more annoying. I will try to refactor code to fit this change soon. 
I think we should go even further and do something like [para Name -> (type, value)]

**Comment by a-enz** [comment]
Implemented
